# Generated by Django 4.1.3 on 2022-11-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_hotels_rooms_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotels',
            new_name='Hotel',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
