# Generated by Django 4.1.3 on 2022-12-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_contact_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
    ]
