# Generated by Django 4.1.3 on 2022-12-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_contact_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flight',
            table='Flight',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='Hotel',
        ),
        migrations.AlterModelTable(
            name='passenger',
            table='Passenger',
        ),
        migrations.AlterModelTable(
            name='place',
            table='Place',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='Reservation',
        ),
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='Ticket',
        ),
        migrations.AlterModelTable(
            name='week',
            table='Week',
        ),
    ]
