# Generated by Django 4.1 on 2022-11-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_destination_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detailed_desc',
            table='Detailed_desc',
        ),
        migrations.AlterModelTable(
            name='pessanger_detail',
            table='pessanger_detail',
        ),
    ]
