# Generated by Django 3.1.2 on 2022-11-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_detailed_desc_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Detailed_desc',
        ),
        migrations.DeleteModel(
            name='pessanger_detail',
        ),
    ]
