# Generated by Django 3.1.2 on 2022-11-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_auto_20221111_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
