# Generated by Django 4.1.3 on 2022-11-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_rename_name_passenger_frist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
