from django.urls import path
from account.views import UserRegistrationView
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('register/done', UserRegistrationView.as_view(), name='registerdone'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('profile', views.profile, name='profile'),
    path('resetPassword', views.resetPassword, name='resetPassword'),
    path("index", views.index, name="index"),
    path("query/places/<str:q>", views.query, name="query"),
    path("flight", views.flight, name="flight"),
    path("review", views.review, name="review"),
    path("flight/ticket/book", views.book, name="book"),
    path("flight/ticket/payment", views.payment, name="payment"),
    path('flight/ticket/api/<str:ref>', views.ticket_data, name="ticketdata"),
    path('flight/ticket/print',views.get_ticket, name="getticket"),
    path('flight/bookings', views.bookings, name="bookings"),
    path('contact', views.contact, name="contact"),
    path('place', views.place, name="place"),
    path('privacy-policy', views.privacy_policy, name="privacypolicy"),
    path('terms-and-conditions', views.terms_and_conditions, name="termsandconditions"),
    path('aboutus', views.aboutus, name="aboutus"),
    path('hotel', views.hotel,name="hotel"),
    path('user/book-room', views.book_room_page,name="bookroompage"),
    path('user/book-room/book', views.book_room,name="bookroom"),
    path('user/bookings', views.user_bookings,name="dashboard"),
    path('addhotel', views.addhotel,name="addhotel"),
    # path('addroom', views.addroom,name="addroom"),
]
